/* eslint-disable global-require */
const images = {
  menu1: require('../../assets/images/yellowCake.png'),
  search1: require('../../assets/images/search.png'),
  checkout1: require('../../assets/images/checkout.png'),
  appLogo: require('../../assets/Image/appLogo.png'),
  avatar: require('../../assets/Image/envelope-of-white-paper.png'),
  lock: require('../../assets/Image/locked.png'),
  hide: require('../../assets/Image/hide.png'),
  detail: require('../../assets/images/img1.png'),
  nodata: require('../../assets/images/nodata.png'),
  // appLogo: require('../../assets/images/logo.png'),
  // back: require('../../assets/images/back.png'),
  // checkBoxOn: require('../../assets/images/checkbox_on.png'),
  // checkBoxOff: require('../../assets/images/checkbox_off.png'),
  // close: require('../../assets/images/close.png'),
  // dropdown: require('../../assets/images/ic_dropdown.png'),
  // faceSad: require('../../assets/images/face_sad.svg'),
  // login: require('../../assets/images/login.png'),
  // modalCamera: require('../../assets/images/modal_camera.png'),
  // modalGallery: require('../../assets/images/modal_gallery.png'),
  // noConnection: require('../../assets/images/no_connection.png'),
  fastFood: require('../../assets/images/fastFood.png'),
  drinks: require('../../assets/images/drinks.png'),
  seafood: require('../../assets/images/seafood.png'),
  desert: require('../../assets/images/desert.png'),
  meal: require('../../assets/images/meal.png'),
  vegetable: require('../../assets/images/vegetable.png'),
  topUp: require('../../assets/images/topup.png'),
  // passOff: require('../../assets/images/padlock_off.png'),
  // passOn: require('../../assets/images/padlock_on.png'),
  // search: require('../../assets/images/ic_search.png'),
  // userOff: require('../../assets/images/user_off.png'),
  // userOn: require('../../assets/images/user_on.png')
  icon_up: require('../../assets/images/upp.png'),
  icon_down: require('../../assets/images/downn.png'),
  mail: require('../../assets/images/mail.png'),
  menu: require('../../assets/images/menu.png'),
  MEJA: require('../../assets/images/MEJA.png'),
  PROMO: require('../../assets/images/PROMO.png'),
  yellowCake: require('../../assets/images/yellowcake1.png'),
  loveIcon: require('../../assets/images/love1.png'),
  bgImage: require('../../assets/images/bgImage.png'),
  otpIlus: require('../../assets/images/otp-ilus.png'),
  inboxActive: require('../../assets/images/inboxActive.png'),
  inboxInactive: require('../../assets/images/inboxInactive.png')
};

export default images;
